[workspace]
members = [
    "cantrip_compressor",
    "cantrip_delay",
    "cantrip_filter",
    "cantrip_gain",
    "xtask",
]
resolver = "2"

[profile.profiling]
debug = 2
inherits = "release"
strip = "none"

[profile.release]
lto = "thin"
strip = "symbols"
